### ISSUE TITLE
getting accesstoken is slow

### ISSUE THREAD

**Issue by MathiasCochet** [okta/okta-oidc-android#124]
Hey,

I am using the okta java authentication sdk to use with a custom built sign in. But when i'm testing my flow on a real device (emulator works fine, which is weird) and I use a debugger, I see that the sessionclient.getTokens() method sometimes takes up to 5 or more seconds to return me the tokens... any idea what causes this ?

**Comment by FeiChen-okta** [comment]
Hi @MathiasCochet What is the device you are using? getTokens have to decrypt the tokens so depending on the device it can take awhile since real devices have different implementations. The emulator doesn't have hardware back keystore or a TEE (trust execution environment) so it won't have this problem. I've had issues with PIXEL 3 where the TEE was taking a long time retrieving the key. The usage of TEE is disabled in the latest SDK release.

**Comment by MathiasCochet** [comment]
@FeiChen-okta i'm using a samsung galaxy s7 edge

**Comment by MathiasCochet** [comment]
@FeiChen-okta I'm also already using the latest version of the library.
This is my gradle setup for okta:
![image](https://user-images.githubusercontent.com/15860179/69809022-28ee9d00-11e9-11ea-87f1-24a07e091971.png)

And this is my configuration in the code:

`
 @Module
 public class OktaLoginServiceModule {

    @Provides
    @Singleton
    public SyncAuthClient provideAuthClient(Context context) {
        OIDCConfig config = new OIDCConfig.Builder()
                .withJsonFile(context, R.raw.okta_oidc_config)
                .create();

        return new Okta.SyncAuthBuilder()
                .withConfig(config)
                .withContext(context)
                .withStorage(new SharedPreferenceStorage(context))
                .setRequireHardwareBackedKeyStore(false)
                .withEncryptionManager(new DefaultEncryptionManager(context))
                .setCacheMode(false)
                .create();
    }

    @Provides
    public SyncSessionClient provideSessionClient(SyncAuthClient authClient) {
        return authClient.getSessionClient();
    }

    @Provides
    @Singleton
    public AuthenticationClient provideAuthenticationClient() {
        return AuthenticationClients.builder()
                .setOrgUrl(BuildConfig.BASE_URL)
                .build();
    }

    @Provides
    public OktaLoginService provideService(final OktaLoginServiceImpl oktaLoginServiceImpl) {
        return oktaLoginServiceImpl;
    }

}
`

**Comment by FeiChen-okta** [comment]
@MathiasCochet I don't see anything wrong with your setup. I don't have a galaxy s7 edge to test but I suspect that it is due to the manufacturers hardware key store implementation. The SDKs default encryption uses RSA. You can try using AES encryption from the example: `EncryptedSharedPreferenceStorage`

**Comment by MathiasCochet** [comment]
@FeiChen-okta, Using the EncryptedSharedPreferences requires your min sdk level to be at 23, so that is not an option.

**Comment by FeiChen-okta** [comment]
Hi @MathiasCochet, Yes it requires API23. The default encryption in the SDK is also in API 23 but defaults to a lower api version based on the device. You'll have to do the same. If the device is lower than API23 you can use the default encryption manager and let it handle it.

**Comment by MathiasCochet** [comment]
Hey @FeiChen-okta, this worked. Thank you for your help!
