### ISSUE TITLE
NullPointerException on 200 response - no "Location" header

### ISSUE THREAD

**Issue by benwicks** [okta/okta-oidc-android#125]
https://github.com/okta/okta-oidc-android/blob/126cf46715bc06a3126e489323ff98cf7448b55a/library/src/main/java/com/okta/oidc/net/request/NativeAuthorizeRequest.java#L66

The response I'm getting has a 200 status code but it does not have a "Location" header. This is causing a NullPointerException on this line. Is this a bug in the library?

**Comment by FeiChen-okta** [comment]
Hi @benwicks The location is needed to get an authorize response where it contains the PKCE code. If it is null then it can be an issue with your Okta org settings. Check if you have set redirect Uri and PKCE for native apps.

**Comment by benwicks** [comment]
Thank you. I believe our org is set up correctly. I am referencing [this documentation](https://developer.okta.com/docs/guides/implement-auth-code-pkce/overview/) to learn about the PKCE flow. I don't understand the part about "Your application directs the browser to the Okta Sign-In page, along with the generated code challenge, and the user authenticates."

We are doing similar to the sample app (https://github.com/okta/samples-android/blob/4ad81ea5bac8c45e4013f1e0977d05f2cc11c9df/custom-sign-in/app/src/main/java/com/okta/android/samples/custom_sign_in/fragments/NativeSignInWithMFAFragment.java#L167) Should we be directing the user to a web page instead/first?

**Comment by FeiChen-okta** [comment]
Hi @benwicks The document you've referenced is for web based applications. You should not need to redirect to web page since you are doing Native sign in.

 The Okta application setup is similar to the web approach outlined here:
https://developer.okta.com/docs/guides/sign-into-mobile-app/android/create-okta-application/

Your settings should look something like
![Screen Shot 2019-12-02 at 3 21 29 PM](https://user-images.githubusercontent.com/46411069/70003302-96ffd080-1517-11ea-8ab4-137e8bf73070.png)
![Screen Shot 2019-12-02 at 3 21 35 PM](https://user-images.githubusercontent.com/46411069/70003316-9d8e4800-1517-11ea-8ec5-8ac28e7bba77.png)
