### ISSUE TITLE
Can't logout form WebAuthClient

### ISSUE THREAD

**Issue by DongNHJVS** [okta/okta-oidc-android#134]
Login works but I have a problems with logout and next login cycle. When I am using logout method from library, in next login cycle webview with login screen is showing but it immediately login user without option to provide login and password manually. Is this normal behaviour? With this kind of login, I can’t instantly login another user after logout. Only sometimes there is option to provide login & password… What it depends on? Can I force providing login & password after every logout? Even after my access and refresh tokens expires it automatically login user. I am using native app configuration + PKCE

Version okta : 1.0.8

**Comment by vantien1401** [comment]
Wait... rep together

**Comment by FeiChen-okta** [comment]
Hi @DongNHJVS, This is normal behavior since the browser have a session. So you have to clear the browser session or wait until it expires.
Signing a user out completely requires the following:
- Remove the tokens.
- Clear the browser session.

For more information please see:
https://github.com/okta/okta-oidc-android#Sign-out

**Comment by DongNHJVS** [comment]
Hi @FeiChen-okta 
I have implemented all functions to logout as your document instructs, but the result is still as I said above.

I have tried many ways but when logging out and clicking on the okta login button, it still does not show the login web view, but it automatically logs in with the previous account.

**Comment by vantien1401** [comment]
Attempt to read from field 'java.lang.String com.okta.oidc.net.request.ProviderConfiguration.end_session_endpoint' on a null object reference
this is error on my applycation, i have used
private var client: WebAuthClient? = null
 client?.let {
                it.sessionClient.clear()
                it.signOutOfOkta(requireActivity())
                it.signIn(requireActivity(), AuthenticationPayload.Builder().build())
            }
but dont success

**Comment by FeiChen-okta** [comment]
Hi @DongNHJVS,

From your code I see the issue. You have to call signOutOfOkta first to clear the browser session. Then call clearData. 
It must be done in this order. The reason is that to clear the browser session it needs the IdToken. If you clear the tokens first then you can’t clear the browser session. Sorry my previous comment on the steps was not in order.

**Comment by FeiChen-okta** [comment]
Hi @vantien1401,

I believe you have the same issue. If you clearData then call signOut then the configuration will be null. 
The order of calling signOut is listed in order from the README: https://github.com/okta/okta-oidc-android/blob/master/README.md#sign-out

My previous comments on the steps are not in order. The readme shows the steps in the correct order.

**Comment by DongNHJVS** [comment]
Hi @FeiChen-okta 

I tried the way you said it, but the result is still the same.
I tried it on the okta dev project and even the product suffers the same situation as above.

**Comment by FeiChen-okta** [comment]
Hi @DongNHJVS,

It looks like you want to sign the user out first in your app. You can do this by checking if the user is already authenticated by using `webAuthClient.sessionClient.isAuthenticated`. If they are signed in then call setupCallback() first. You should setup the callbacks first so you can get the status of signOutOfOkta. Call signOutOfOkta then in the onSuccess() method of the callback call clearData(). This way you can check the error message that is returned if signOut is unsuccessful.

You can use the following as reference:
https://github.com/okta/samples-android/blob/master/sign-in-kotlin/app/src/main/java/com/okta/oidc/MainActivity.kt

**Comment by DongNHJVS** [comment]
Hi @FeiChen-okta 

![image](https://user-images.githubusercontent.com/40257252/72038437-f0f07480-32d3-11ea-89b0-48c2ef0183db.png)

I tried to implement as you have suggested, but still an error like @vantien1401 
 above.

This is error : LoginActivity$setupCallback$callback: Okta error mes Log out error, AuthorizationException: {"type":4,"code":4001,"error":"invalid_redirect_uri"}

**Comment by FeiChen-okta** [comment]
Hi @DongNHJVS, Check your `mOidcConfig` to see if you have the redirect_uri setup correctly. The exception is showing that you have an invalid redirect uri. If you are using a json file like:
```json
{
  "client_id": "{clientId}",
  "redirect_uri": "{redirectUri}",
  "end_session_redirect_uri": "{endSessionUri}",
  "scopes": [
    "openid",
    "profile",
    "offline_access"
  ],
  "discovery_uri": "https://{yourOktaDomain}"
}
```
Make sure URIs for both redirect and end session are correctly configured on your okta server. For the okta server setup: https://developer.okta.com/quickstart/#prerequisites

**Comment by vantien1401** [comment]
![image](https://user-images.githubusercontent.com/10338809/72039408-93f6bd80-32d7-11ea-8fa1-f630e8f7d18c.png)
Hi @FeiChen-okta I have debuged but this is my error

**Comment by FeiChen-okta** [comment]
Hi @vantien1401, It looks like your ProviderConfiguration is null. You can do a check to see if the user is authenticated by `webAuthClient.sessionClient.isAuthenticated` then attempt to sign out.
Since clearData() will remove the ProviderConfiguration also. The provider configuration is obtained during signIn(). So if you have called clearData before then the configuration doesn't exist. Attempting to signOut with a non existing configuration will cause that error so its best to check if the user `isAuthenticated` first.

**Comment by FeiChen-okta** [comment]
Hi @vantien1401 @DongNHJVS One thing to note is that you can only signOut if user is signed in because sign out requires the idToken and the end_session endpoint in the configuration. So in your app startup you should check if the user is signed in using `isAuthenticated` if they are signed in then proceed with sign out flow. hope this clears up the confusion.

**Comment by DongNHJVS** [comment]
Hi @FeiChen-okta 

This is my config : 
![image](https://user-images.githubusercontent.com/40257252/72045733-6ca8ec00-32e9-11ea-8902-927d492861a5.png)

When isAuthenticated = false, the logout method is not called, but clicking the login button will automatically log in without allowing account changes.
When isAuthenticated = true, the logout method is called, but there is no return from the callback or event being registered.
Clicking the login button will still automatically login without allowing account changes.

**Comment by FeiChen-okta** [comment]
Settings look correct. I'm not certain what the issue is here. I can think of only moving the clearData() call to onSuccess(). 
```kotlin
            override fun onSuccess(result: AuthorizationStatus) {
                network_progress.hide()
                when (result) {
                    AUTHORIZED -> signInSuccess()
                    SIGNED_OUT -> webAuthClient.sessionClient.clear()
                }
            }
```
A couple of other things to try:
1. manually clear your browser cache by going to the devices settings -> apps menu and clear it.
2. Try using your server configuration with the sample app
https://github.com/okta/samples-android/tree/master/sign-in-kotlin
3. Set a short session timeout in the server: 
https://devforum.okta.com/t/session-expiration-using-the-org-authorization-server-oidc/2059

**Comment by vantien1401** [comment]
Thanks @FeiChen-okta

**Comment by DongNHJVS** [comment]
Thanks @FeiChen-okta .
I have fix this issue, thanks for support.
I will close this issue.

**Comment by rajeshbandala** [comment]
@DongNHJVS What was the fix for this issue. i followed all the details in documentation and this post. still see the same issu.

**Comment by DongNHJVS** [comment]
> @DongNHJVS What was the fix for this issue. i followed all the details in documentation and this post. still see the same issue.

When you press the logout button, you should call client.signOutOfOkta (requireActivity ()) first.
Do not call client.sessionClient.clear () because you called here, the logout operation will be canceled, so call client.sessionClient.clear () in the callback:
when (result) {
                     AUTHORIZED -> signInSuccess ()
                     SIGNED_OUT -> client.sessionClient.clear ()
 }

**Comment by rajeshbandala** [comment]
> > @DongNHJVS What was the fix for this issue. i followed all the details in documentation and this post. still see the same issue.
> 
> When you press the logout button, you should call client.signOutOfOkta (requireActivity ()) first.
> Do not call client.sessionClient.clear () because you called here, the logout operation will be canceled, so call client.sessionClient.clear () in the callback:
> when (result) {
>                      AUTHORIZED -> signInSuccess ()
>                      SIGNED_OUT -> client.sessionClient.clear ()
> }

@DongNHJVS Applied this solution. but if I sign-in with another user in the same domain it's still bypassing the authentication and signing in with the previous user.

**Comment by DongNHJVS** [comment]
@rajeshbandala I also have the same case, When you call client.signOutOfOkta(), it will open the browser and immediately turn it off.
If not, then you need to check client.sessionClient.isAuthenticated, if false then there is error in getting client.

**Comment by sahibazad** [comment]
@DongNHJVS @rajeshbandala I am also stuck in a similar issue. Has anyone been able to solve the logout part that can simply logout and not maintain any session. So that if I try to login with a separate user, it doesn't bypass and login with the old user instead.

I've tried the above solution by @FeiChen-okta but still no luck.

**Comment by DongNHJVS** [comment]
@sahibazad There are my code : 
implementation 'com.okta.android:oidc-androidx:1.0.2'

<img width="941" alt="Screen Shot 2020-05-27 at 16 18 12" src="https://user-images.githubusercontent.com/40257252/83001264-b5153c00-a035-11ea-81e5-dbbf7d1cfbd0.png">

Hope be fine.

**Comment by sahibazad** [comment]
> @sahibazad There are my code :
> implementation 'com.okta.android:oidc-androidx:1.0.2'
> 
> <img alt="Screen Shot 2020-05-27 at 16 18 12" width="941" src="https://user-images.githubusercontent.com/40257252/83001264-b5153c00-a035-11ea-81e5-dbbf7d1cfbd0.png">
> 
> Hope be fine.

Hi @DongNHJVS thanks for the code. I'll try this. Hopefully it works!

**Comment by wmgandresg** [comment]
@sahibazad I do have exactly the same issue, I've been trying to logout and then login with a different user that has the same domain and the web flow gets the previous session. I tried everything described in this thread and I'm still having the same problem, it works perfectly if I use a user with a different domain. Did you fixed that on your side?

**Comment by sahibazad** [comment]
@wmgandresg unfortunately no. It was not possible, and nothing here worked for me either. Since we were using another LDAP via Okta, so we had to decrease the session timeout for that LDAP instead to create a makeshift solution at the time.

**Comment by satyajitvure91** [comment]
Hey @wmgandresg @sahibazad I am stuck in the same situation as you guys were. I'm trying to see if anyone of you have found a solution to this.

**Comment by alizaidi606** [comment]
Any update on this, I am having the same issue.

**Comment by JayNewstrom** [comment]
Please open a new issue describing your problem.
