### ISSUE TITLE
Registration Endpoint not optinal issue

### ISSUE THREAD

**Issue by bedirguven** [okta/okta-oidc-android#135]
hi guys,

Is it possible to make the registration endpoint parameter optional for authentication with okta?Because we cannot get a registration endpoint from the well-known configuration. So we can't open login web page.

We are using app auth now and we don't use registration_endpoint for login.

Thanks.

**Comment by FeiChen-okta** [comment]
Hi @bedirguven,

The ProviderConfiguration is not exposed at the moment. The OIDC spec says the well-known is optional but we didn't see a benefit of not having it since it increases the chances of incorrect configuration. I can expose the configuration in the setup steps, I'll track this internally as a feature request.

**Comment by FeiChen-okta** [comment]
Added `CustomConfiguration` option in `1.0.9`
