### ISSUE TITLE
Two application icons are displayed when I am running Sample app.

### ISSUE THREAD

**Issue by gopalp1709** [okta/okta-oidc-android#152]

**Comment by gopalp1709** [comment]
How to display one app icon ? please share a link which provides steps to integrate SDK for android application.

**Comment by FeiChen-okta** [comment]
Hi @gopalp1709 The sample app has two icons because in the AndroidManifest it specifies that. It is by design because the sample shows how to use the SDK if you extend Activity or extend FragmentActivity and any of its child activities. More information on [AndroidManifest](https://developer.android.com/guide/topics/manifest/manifest-intro)

More information on okta's developer site: https://developer.okta.com/code/android/

**Comment by gopalp1709** [comment]
Thanks for reference.
