### ISSUE TITLE
Cannot login after unsuccessful try

### ISSUE THREAD

**Issue by alexzaitsev** [okta/okta-oidc-android#157]
**Steps:**
1. Try to login with user not assigned to app 
2. Receive authorization error AuthorizationException: `{"type":1,"code":1002,"error":"access_denied","errorDescription":"User is not assigned to the client application."}`
3. Try to login again
```
authClient.registerCallback(loginCallback, activity)
authClient.signIn(activity, authPayload)
```

**The same authorization error is thrown.** That's definitely a bug because I am not even prompted for login/password. What to do if I want to login with another user after that unsuccessful try? For now I have to reinstall the app.
**How can I fix that?** @FeiChen-okta perhaps you can point to a specific line in the code?

**Comment by alexzaitsev** [comment]
A bit more digging showed that that first URL that the app is trying to show on step 3 (see the instruction from my previous message) is `myshema:/callback?state=someIdHere&error=access_denied&error_description=User+is+not+assigned+to+the+client+application.`
It looks like the session is kept forever.
If I try to signOut before the signing in `authClient.signOut(activity, LOGOUT_FLAGS, logoutCallback)` I get `BaseAuth.FAILED_CLEAR_SESSION` error.
Looking for your help.

**Comment by FeiChen-okta** [comment]
Hi @alexzaitsev The only way to clear a session is if you have an `idToken`. But since you can't do the code exchange you are not signed in. This might be an issue with the web app since it should not save the session if the sign-in failed. Need to investigate more. 

For now I have a few workarounds:
Are you using the webview approach? if so you can clear cookies using [cookie manager](https://developer.android.com/reference/android/webkit/CookieManager).

If using Chrome you have to disable persistent cookies on the org. You can follow the instructions on how to do it here: https://developer.okta.com/docs/guides/shared-sso-android-ios/ios/session-and-persistent-sso/
But set `usePersistentCookie` to false.

**Comment by alexzaitsev** [comment]
I use a webview approach. Clearing the cookines using cookie manager works! Thanks a lot for your support.
