### ISSUE TITLE
Support for Pre and Post request delegate functionality to support Shape

### ISSUE THREAD

**Issue by seanvancity** [okta/okta-oidc-android#162]
Both Shape and Okta have SDKs that are opaque to us. 

Okta has a standard SDK where we ask for something at a high level, and the requests are carried out behind the scenes.

Shape has an SDK where it wants to be given the low-level request object prior to it being sent, and be handed the response for further processing after it has been received.

In order to integrate Okta with Shape, we need to grant Shape access to the requests and responses that Okta is generating.

Approach
We ask for two new callbacks to be added to the Okta SDK.

Example from iOS issues - (Android example TBD):

```
protocol OktaHttpDelegate {
    
    /// Called after request creation, just before send.
    func willSend(request: NSMutableURLRequest)
    
    /// Called after response received, just after receipt.
    func didReceive(response: HTTPURLResponse)
    
}
```

![OktaShapeFlow](https://user-images.githubusercontent.com/20363572/83313186-fccccc80-a1c9-11ea-9ddb-8e5defc76294.jpg)

Will be repeating this issue for the Android Auth Java library and similar approach on the equivalent iOS SDKs

**Comment by chriswrightlulu** [comment]
Hi @FeiChen-okta ,

Can you please be more specific?  I don't see any interface on com.okta.authn.sdk.client.AuthenticationClient that would allow us to specify the HTTP client.

Are you referring to some generic feature of the OS that allows override of one of the 3 types of HTTP client commonly used on Android?

Thanks,
Chris

**Comment by FeiChen-okta** [comment]
Hi @chriswrightlulu,

The authn sdk allows you to use either apache httpclient or okhttpclient. You can also provide your own if you implement 
https://github.com/okta/okta-commons-java/blob/master/http/okhttp/src/main/java/com/okta/commons/http/okhttp/OkHttpRequestExecutorFactory.java

Another way is to extend DefaultAuthenticationClient and override `createRequestExecutor` to create your own `RequestExecutor` with your own networking stack. We can provide examples if you would like.

But before doing that does adding headers work for your use case? https://github.com/okta/okta-auth-java#setting-request-headers-parameters-and-device-fingerprinting

**Comment by chriswrightlulu** [comment]
Thanks FeiChen-okta,

Adding headers will not work because Shape's SDK is trying to sign the complete request somehow, so pre-adding the data would make the signature incorrect.

I don't wish to globally override the DefaultAuthenticationClient so I don't think that one will work.

The OkHttpRequestExecutorFactory override looks more promising, assuming that I'm only overriding it for your own SDK.  Do you have an example of how that is done, and what methods I would call on your own SDK in order to introduce that new request executor into its flow?

Thanks,
Chris

**Comment by FeiChen-okta** [comment]
Hi @chriswrightlulu I have written a sample on how to override the request executor and posted the PR here
https://github.com/okta/samples-android/pull/49

This is the location where you want to put your custom headers before the connection.
https://github.com/okta/samples-android/blob/custom-request-executor/sign-in-kotlin/app/src/main/java/com/okta/oidc/http/CustomRequestExecutor.kt#L37

I had to rewrite the `DefaultAuthenticationClientBuilder` because the `ClientConfiguration` wasn't exposed. If the configuration was exposed by `DefaultAuthenticationClientBuilder` then then custom client builder can override build and use the same configuration to create the custom client.

**Comment by chriswrightlulu** [comment]
Thanks @FeiChen-okta ,

This does indeed look like it will work.  We'll try it out and get back to you.

Cheers,
Chris
