### ISSUE TITLE
Sing out is not signing out

### ISSUE THREAD

**Issue by akolubau** [okta/okta-oidc-android#212]
My log out code is following

```
client.sessionClient.tokens?.refreshToken?.let { client.sessionClient.revokeToken(it, revokeTokenCallback) }
client.sessionClient.tokens?.accessToken?.let { client.sessionClient.revokeToken(it, revokeTokenCallback) }
client.signOutOfOkta(activity)
client.sessionClient.clear()
```

But after sign out when I press login button activity with web view appears for a half of a second and immediately response with tokens for my previous logged-in user. So, actually, I'm unable to enter another user credentials and log out is actually not log out at all. Any suggestions to solve the problem?

**Comment by JayNewstrom** [comment]
This is likely due to a few issues.

Please ensure you're calling the sign out methods in the correct order. Please see our documentation here: https://github.com/okta/okta-oidc-android#sign-out

You'll also want to wait for the callbacks to be called before moving to the next step. 

These APIs are not meant to be called in parallel. Please wait to call the next API from the previous callback.

**Comment by akolubau** [comment]
TY, this really helped.
