### ISSUE TITLE
Wrong error during signIn without network connection

### ISSUE THREAD

**Issue by Max2817** [okta/okta-oidc-android#214]
Hi,
Thank you for your job on this library. It's very useful!

I have a weird behaviour when I try to call 
`void signIn(@NonNull Activity activity, AuthenticationPayload payload)`
without Internet connection.
As a result in my callback I get a 
`AuthorizationException: {"type":0,"code":0,"errorDescription":"Unable to resolve host \"myDiscoveryUrl\": No address associated with hostname"}`
instead of getting a network error like:
```
/**
* Indicates a network error occurred.
*/
public static final AuthorizationException NETWORK_ERROR = generalEx(3, "Network error");
```
Everything works fine when I have Internet connection.
I don't know if it's related but is it possible that it could be caused by the fact that the 
```
catch (Exception e) {
            throw AuthorizationException.fromTemplate(AuthorizationException
                    .GeneralErrors.NETWORK_ERROR, e);
        } 
```
is the last one in 
`public TokenResponse executeRequest(OktaHttpClient client) throws AuthorizationException` in TokenRequest.java?

Thank you in advance

**Comment by JayNewstrom** [comment]
Hi @Max2817 thanks for the kind words!

This error is by design, and is happening due to the HTTP Client throwing an `IOException`. https://github.com/okta/okta-oidc-android/blob/35c222c01ef41e7c69939af8c7aad4eaa0472146/library/src/main/java/com/okta/oidc/net/request/AuthorizedRequest.java#L63

If you need to do something special in your application layer for these errors, you can access the root cause `IOException` by calling `exception.getCause()`.

**Comment by Max2817** [comment]
Thank you @JayNewstrom , I check this ASAP.

**Comment by Max2817** [comment]
Getting the cause returns me a UnknownHostException. I guess can't get a NetworkException due to the HTTP Client you mentioned. I will deal with this Exception. Thank you
