### ISSUE TITLE
Okta Browser login not supported on Samsung internet browser.

### ISSUE THREAD

**Issue by gopalp1709** [okta/okta-oidc-android#252]
Hi Team,
Okta Browser login not supported on Samsung internet browser. It's throwing incompatible browser exception because Samsung Internet as default browser. I am using 
` val builder = Okta.WebAuthBuilder()
                            .browserMatchAll(true)
                            .withConfig(mOidcConfig)
                            .withContext(context.applicationContext)
                            .withStorage(SharedPreferenceStorage(context))
                            .withTabColor(context.resources.getColor(R.color.colorPrimary)) //.supportedBrowsers(defaultBrowser)c
                            .supportedBrowsers(ANDROID_BROWSER, FIRE_FOX, CHROME,SAMSUNG)`

I can not ask production user to install and change default browser to Chrome , please provide any solution.
Using below dependencies:
`    implementation 'com.okta.android:okta-oidc-android:1.0.19'
    implementation "androidx.browser:browser:1.3.0"`

**Comment by JayNewstrom** [comment]
Hi, our current implementation only allows use of browsers that support [chrome custom tabs](https://developer.chrome.com/docs/android/custom-tabs/overview/)

Due to this, you'll have to catch this exception, and ask the user to install a supported browser. If this doesn't fit with your UX, please consider using our Rest APIs directly with one of our [SDKs](https://github.com/okta/okta-auth-java). This will allow you to fully control the user experience, but comes with more effort as the developer.

The reason we require chrome or similar (ex Firefox is also supported), is due to the wide range of feature we support (ie [WebAuthn](https://help.okta.com/en/prod/Content/Topics/Security/mfa-webauthn.htm)).

**Comment by NikitaAvraimov-okta** [comment]
You can also check https://github.com/okta/samples-android/tree/master/custom-sign-in out, custom sign-in sample demonstrates how to use our sdk without chrome custom tabs

**Comment by gopalp1709** [comment]
Can SSO work with this native login ?
