### ISSUE TITLE
Android Pie Emulator Login Exception

### ISSUE THREAD

**Issue by davidhartley** [okta/okta-oidc-android#89]
On Emulator only, I see an AuthorizationException when trying to login on Anroid Pie (9). Previous versions of Android work fine.

Here is the exception:
AuthorizationException: {“type”:4,“code”:5002,“error”:“Hardware Backed KeyStore. Client require hardware backed keystore, but EncryptionManager doesn’t support it.“}

Is there a recommended path for running Pie+ in emulator with Okta for login?

**Comment by davidhartley** [comment]
@FeiChen-okta it's the browser part. The browser doesn't log out - I'm guessing it's the same AuthroizationException about Hardware Backed keystore but I don't have access to the physical device to debug it and I can't replicate in an emulator because of the above.

**Comment by davidhartley** [comment]
It is a Pixel 3 device just in case it matters.

**Comment by FeiChen-okta** [comment]
Might be related to issue #90 I found that the Pixel3 with Android 9 have issues with decryption.

```bash
javax.crypto.IllegalBlockSizeException
	at android.security.keystore.AndroidKeyStoreCipherSpiBase.engineDoFinal(AndroidKeyStoreCipherSpiBase.java:519)
```
So when logging out the id token and other information needs to be decrypted before it can do the logout. One way to see if this is the issue is to mock the EncryptionManager and return input  string in decrypt/encrypt.

For reference:
https://github.com/okta/okta-oidc-android/blob/master/library/src/test/java/com/okta/oidc/util/EncryptionManagerStub.java

**Comment by FeiChen-okta** [comment]
@davidhartley See if the new release fixes the issue. see notes in #90 for more info.
